name: Project CI/CD Flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # A침adido: Permiso para que GITHUB_TOKEN pueda subir el gr치fico de dependencias
    permissions:
      contents: write

    steps:
      # 1. Checkout del repositorio
      - uses: actions/checkout@v4

      # 2. Configurar JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Build con Maven
      - name: Build with Maven
        run: mvn -B clean install

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      # 4. Construir la imagen Docker
      - name: Build Docker image
        run: |
          # 1. Creamos la etiqueta din치mica
          IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-8)
          
          # 2. Construimos la imagen con la etiqueta SHA
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/github-cicd-actions:${IMAGE_TAG} .
          
          # 3. Le asignamos la etiqueta 'latest' a la misma imagen construida
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/github-cicd-actions:${IMAGE_TAG} ${{ secrets.DOCKERHUB_USERNAME }}/github-cicd-actions:latest

      # 5. Iniciar sesi칩n en Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Subir la imagen al Docker Hub
      - name: Push Docker image
        run: |
          IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-8)
          
          # Subimos la imagen con etiqueta SHA
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/github-cicd-actions:${IMAGE_TAG}
          
          # Subimos la imagen con etiqueta latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/github-cicd-actions:latest
